### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by SrMonsterYT** [Slimefun-Addon-Community/HeadLimiter#22]
slimefun version and addons: https://prnt.sc/dW2_3EQ7cnzM

HeadLimiter is increasing the memory a lot, my server barely restarted and already hit 25GB, and his normal is always 20GB, when it comes to night the server is almost 28GB, when removing the addon I noticed that there was no more increase in ram memory.

that's only 10m servers online, after a restart: https://prnt.sc/cmrP7uyzNpU4

my configuration: https://mclo.gs/VY3JiVB

**Comment by J3fftw1** [comment]
Can I get a spark report from when the server starts for 15min

**Comment by SrMonsterYT** [comment]
> Can I get a spark report from when the server starts for 15min

spark shows nothing https://spark.lucko.me/YZtmDFmfJI

**Comment by J3fftw1** [comment]
it looked like you deleted your spark report comment.
I need some information.
Can you run the following commands and let them finish before starting the next command.
/spark profiler start --thread * --timeout 900
/spark health --memory
/spark heapsummary `use when the server has high memory`
/spark heapdump `use when the server has high memory`

if these dont give enough info we have to dig deeper.

**Comment by SrMonsterYT** [comment]
ok

**Comment by SrMonsterYT** [comment]
> it looked like you deleted your spark report comment. I need some information. Can you run the following commands and let them finish before starting the next command. /spark profiler start --thread * --timeout 900 /spark health --memory /spark heapsummary `use when the server has high memory` /spark heapdump `use when the server has high memory`
> 
> if these dont give enough info we have to dig deeper.

so?

**Comment by J3fftw1** [comment]
Patience I have a job besides working at Headlimiter. All these reports are pretty in depth and I need time to work on it. I will
Let you know if I find something

**Comment by J3fftw1** [comment]
Okay what i think is happening.

Headlimiter checks every chunk if it has x amount of blocks.
by checking that its adding its results to a cache in memory.
These results are kept till the server shutsdown.
The longer the server runs the more chuncks are checked.
What i could do is add a period of how long they should stay in the chunk for but that would mean there are more spikes.
To add on this though Headlimiter only uses 667KB in memory.
Which is nothing.
This is not a Headlimiter issue.
Also when you ran this your server had 12gb of memory used if you want me to check this properly run. /spark heapdump when its at like 20gb. you can ping me on discord since i will be closing this ticket
